# author: github.com/hmasum52
name: test Build

on:
  push:
    branches: [ release ]

  workflow_dispatch: # Manually trigger the workflow

jobs:
  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from app/build.gradle.kts
        id: extract_version
        run: |
          version=$(grep 'versionName' app/build.gradle.kts | cut -d '"' -f 2)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if Tag Exists
        id: check_tag
        run: |
            if git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
                echo "TAG_EXISTS=true" >> $GITHUB_ENV
            else
                echo "TAG_EXISTS=false" >> $GITHUB_ENV
            fi

      - name: Modify Tag if Exists
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false